### ISSUE TITLE
ระบบจ่ายเงิน

### ISSUE THREAD

**Issue by Yay50210** [Yay50210/comPo#12]
ช่องทางการจ่ายเงิน

**Comment by Sata-P** [comment]
#include "payment.h"
#include "./ui_payment.h"
#include <QDebug>
#include <QMessageBox>
#include <QString>
#include <QRandomGenerator>
#include"otp.h"


MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::on_okbutton_clicked()
{
    QString creditCardNumber = ui->creditinput->text();
    QString cvv = ui->cvvinput->text();


    if (check_credit_num(creditCardNumber) && check_credit_cvv(cvv) == true) {
        otp = new class otp(this);
        otp->show();

    } else if((check_credit_num(creditCardNumber)==false && check_credit_cvv(cvv) == true)){
        QMessageBox::warning(this, "Error", "Invalid Credit Card");
    }else if((check_credit_num(creditCardNumber)==true && check_credit_cvv(cvv) == false)){
        QMessageBox::warning(this, "Error", "Invalid CVV");
    } else if((check_credit_num(creditCardNumber)==false && check_credit_cvv(cvv) == false)){
        QMessageBox::warning(this, "Error", "Invalid Credit Card Code and Invalid CVV");
    }
}

bool MainWindow::check_credit_num(const QString &creditCardNumber)
{
    int sum = 0;
    bool alternate = true;

    if(creditCardNumber.length()==16||creditCardNumber.length()==15||creditCardNumber.length()==19){
    for (int i = 0; i < creditCardNumber.length(); ++i) {
        QChar digit = creditCardNumber.at(i);

        if (digit.isDigit()) {
            int digit_num = digit.digitValue();

            if (alternate) {
                digit_num *= 2;
                if (digit_num > 9) {
                    digit_num = (digit_num % 10) + 1;
                }
            }

            sum += digit_num;
            alternate = !alternate;
        } else {
            continue;
        }
    }
    }else{
        sum=1;
    }
    return (sum % 10 == 0);
    }


bool MainWindow::check_credit_cvv(const QString &cvv)
{
    int count_cvv = 0;

    for (int j = 0; j < cvv.length(); j++) {
        QChar digit_cvv = cvv.at(j);

        if (digit_cvv.isDigit()) {
            int digitValue = digit_cvv.digitValue();

            if (digitValue >= 0 && digitValue <= 9) {
                count_cvv++;
            } else {
                return false;
            }
        } else {
            continue;
        }
    }

    return (count_cvv == 3);
}

**Comment by Sata-P** [comment]
#include "otp.h"
#include "ui_otp.h"
#include <QRandomGenerator>
#include <QMessageBox>

otp::otp(QWidget *parent)
    : QDialog(parent)
    , ui(new Ui::otp)
{
    ui->setupUi(this);
}

otp::~otp()
{
    delete ui;
}

void otp::on_pushButton_2_clicked()
{
    generatedOTP = GenerateOTP(6);
    qDebug() << "your OTP is " << generatedOTP;
}

QString otp::GenerateOTP(int length)
{
    QString otp;
    for (int i = 0; i < length; i++) {
        otp.append(QString::number(QRandomGenerator::global()->bounded(10)));
    }
    return otp;
}

void otp::on_pushButton_clicked()
{
    QString randomOTP = ui->otpinput->text();

    if (randomOTP == generatedOTP) {
        QMessageBox::information(this, "", "Purchased");
         qApp->quit();//when clicked ok app will quit suddenly
    }else{
        QMessageBox::warning(this, "", "OTP Not Correct");
    }
    }

**Comment by Sata-P** [comment]
ยังไม่ได้เอาไปรวมกับอันหลักอันนี้สร้างไฟล์แยกไว้
