### ISSUE TITLE
การแจ้งขอความช่วยเหลือ 

### ISSUE THREAD

**Issue by Yay50210** [Yay50210/comPo#15]
ช่องทางการติดต่อหาเจ้าของที่ เพื่อดูเรื่องความไม่เรียบร้อย 
เช่น ไฟไม่ติด แอร์ไม่เย็น

***ใส่ช่องทางการติดต่อของ เจ้าของ เบอร์ หรือ facebook

**Comment by Buburry** [comment]
![สกรีนช็อต 2024-02-26 124245](https://github.com/Yay50210/comPo/assets/141802154/ce3d6cfc-b20f-4d6c-9db0-4907c23b14eb)
![Uploading สกรีนช็อต 2024-02-26 124312.png…]()

**Comment by Buburry** [comment]
[CMakeLists.txt](https://github.com/Yay50210/comPo/files/14400733/CMakeLists.txt)
