### ISSUE TITLE
ค้นหาห้องพัก

### ISSUE THREAD

**Issue by Yay50210** [Yay50210/comPo#18]
พิมพ์ชื่อ/เลขห้องพักเพื่อหาห้องพัก

**Comment by Buburry** [comment]
vs code gui

**Comment by Khunsukkub** [comment]
#include<iostream>
#include<fstream>
#include<vector>
#include<string>
#include<cstdlib>

using namespace std;

string toUpperStr(string x){
    string y = x;
    for(unsigned i = 0; i < x.size();i++) y[i] = toupper(x[i]);
    return y;
}

void importDataFromFile(string filename,vector<string> &info,vector<string> &rooms,vector<string> &status){
    ifstream infomations (filename);
    
    string line;
    
    while(getline(infomations, line)){
        rooms.push_back(line.substr(0, line.find(':')-1));
        line.erase(0, line.find(':') + 2);
        status.push_back(line.substr(0, line.find(':')-1));
        line.erase(0, line.find(':') + 2);
        info.push_back(line.substr(line.find_first_not_of(" "), line.find_last_not_of(" ") + 1));
    }

}

void getCommand(string &command,string &key, int rkey){
    
        string input;
    
        // บรรทัดนี้ใส่ code ที่จะสามารถรับข้อมูลจาก แถบค้นหา *************************
        getline(cin,input);
        
        size_t space = input.find_first_of(' ');
        
        command = input.substr(0,space);
        key = input.substr(space+1);
        
        for(int i = 0 ; i < 10 ; i++){ //เอาไว้เช็ค ว่า key ที่ได้รับมามันเป็น เลขห้อง หรือ สถานะห้อง
                if(key[key.size()] == i){
                        rkey = stoi(key);
                        key = "";
                        break;
                }
        }
    
}

void searchRooms(vector<string> &info,vector<string> &rooms,vector<string> &status,int &rkey){
    
    cout << "---------------------------------------------------------------" << endl;
    
    unsigned int i = 0;
    while(i < rooms.size()){
        if(stoi(rooms[i]) == rkey){
                cout << endl;
                cout << "ห้องหมายเลข : " << rooms[i] << endl;
                cout << endl;
                cout << "สถานะ : " << status[i] << endl;
                cout << endl;
                cout << "รายละเอียด : " << info[i] << endl;
                cout << endl;
                cout << "---------------------------------------------------------------" << endl;
                break;
            }
        i++;
    }
    if(i == rooms.size()){
            cout << endl;
            cout << "ไม่พบห้องพักดังกล่าว";
            cout << endl;
            cout << "---------------------------------------------------------------" << endl;
        }

}

void searchMT(vector<string> &info,vector<string> &rooms,vector<string> &status,string &key){
    
    cout << "---------------------------------------------------------------" << endl;
    unsigned int i = 0;
    unsigned int pass = 0;
    while(i < rooms.size()){
        cout << endl;
        if(status[i] == key && pass == 0) cout << "ห้องว่างที่สามารถเข้าพักได้ : " << endl;
        if(status[i] == key){
            cout << "ห้องหมายเลข : " << rooms[i] << endl;
            cout << endl;
            cout << "รายละเอียด : " << info[i] << endl;
            pass++;
        }
        i++;
    }
    if(i == rooms.size() && pass == 0) cout << "ไม่พบห้องพักที่สามารถเข้าพักได้" << endl;
    
    cout << endl;
    cout << "---------------------------------------------------------------" << endl;
    
}

int main(){
    string filename = "______"; //ชื่อไฟล์ข้อมูล***************************
    vector<string> info;
    vector<string> rooms;
    vector<string> status;
    importDataFromFile(filename, info, rooms, status);
    
    do{
        string command, key;
        int rkey = 0;
        getCommand(command,key,rkey);
        key = toUpperStr(key);
        command = toUpperStr(command);
        if(command == "______") break; // กด X เพื่อออกจากแถบค้นหา
        else if(command == "ROOMS") searchRooms(info, rooms, status, rkey);
        else if(command == "STATUS") searchMT(info, rooms, status, key);
    }while(true);
    
    return 0;
}

**Comment by Khunsukkub** [comment]
ตอนนี้ ระบบค้นหา
- ค้นหาห้องพักที่ต้องการ โดย การรับ Input เป็น ตัวเลข เพื่อค้นหาห้องพักนั้นๆ โดย จะบอก หมายเลขห้อง , สถานะ , ข้อมูลห้องพัก
- ค้นหาห้องพักที่ยังว่างอยู่ โดย การับ Input เป็น String "Empty" เพื่อค้นหาห้องพักทั้งหมดที่ยังคงว่างอยู่ โดย จะบอก หมายเลขห้องพัก และ รายละเอียดห้องพัก

**Comment by Khunsukkub** [comment]
ตอนนี้ อยากให้ ใน File ข้อมูล แบ่งเป็นแบบ "หมายเลขห้อง : ราคา : สถานะ : ข้อมูลห้องพัก"

**Comment by Khunsukkub** [comment]
#include<iostream>
#include<fstream>
#include<vector>
#include<string>
#include<cstdlib>

using namespace std;

string toUpperStr(string x){
    string y = x;
    for(unsigned i = 0; i < x.size();i++) y[i] = toupper(x[i]);
    return y;
}

void importDataFromFile(string filename,vector<string> &info,vector<string> &rooms,vector<string> &cost,vector<string> &status){
    ifstream infomations (filename);
    
    string input;
    
    while(getline(infomations, input)){
        rooms.push_back(input.substr(0,input.find(':')-1));
        input.erase(0,input.find(':')+2);
        cost.push_back(input.substr(0, input.find(':')-1));
        input.erase(0,input.find(':')+2);
        status.push_back(input.substr(0, input.find(':')-1));
        input.erase(0,input.find(':')+2);
        info.push_back(input.substr(0, input.find(':')-1));
    }

}

void getCommand(string &command,string &key, int rkey){
    
        string input;
    
        // บรรทัดนี้ใส่ code ที่จะสามารถรับข้อมูลจาก แถบค้นหา *************************
        getline(cin,input);
        
        size_t space = input.find_first_of(' ');
        
        command = input.substr(0,space);
        key = input.substr(space+1);
        
        for(int i = 0 ; i < 10 ; i++){ //เอาไว้เช็ค ว่า key ที่ได้รับมามันเป็น เลขห้อง หรือ สถานะห้อง
                if(key[key.size()-1] == i){
                        rkey = stoi(key);
                        key = "";
                        break;
                }
        }
    
}

void searchRooms(vector<string> &info,vector<string> &rooms,vector<string> &cost,vector<string> &status,int &rkey){
    
    cout << "---------------------------------------------------------------" << endl;
    
    unsigned int i = 0;
    while(i < rooms.size()){
        if(stoi(rooms[i]) == rkey){
                cout << endl;
                cout << "ห้องหมายเลข : " << rooms[i] << endl;
                cout << endl;
                cout << "ราคา : " << cost[i] << " บาท ต่อ คืน" << endl;
                cout << endl;
                cout << "สถานะ : " << status[i] << endl;
                cout << endl;
                cout << "รายละเอียด : " << info[i] << endl;
                cout << endl;
                cout << "---------------------------------------------------------------" << endl;
                break;
            }
        i++;
    }
    if(i == rooms.size()){
            cout << endl;
            cout << "ไม่พบห้องพักดังกล่าว";
            cout << endl;
            cout << "---------------------------------------------------------------" << endl;
        }

}

void searchST(vector<string> &info,vector<string> &rooms,vector<string> cost ,vector<string> &status,string &key){
    
    cout << "---------------------------------------------------------------" << endl;
    unsigned int i = 0;
    unsigned int pass = 0;
    while(i < rooms.size()){
        cout << endl;
        if(status[i] == key && pass == 0) cout << "ห้องว่างที่สามารถเข้าพักได้ " << endl;
        cout << endl;
        if(status[i] == key){
            cout << "ห้องหมายเลข : " << rooms[i] << endl;
            cout << "ราคา : " << cost[i] << " บาท ต่อ คืน" << endl;
            cout << "รายละเอียด : " << info[i] << endl;
            cout << endl;
            pass++;
        }
        i++;
    }
    if(i == rooms.size() && pass == 0) cout << "ไม่พบห้องพักที่สามารถเข้าพักได้" << endl;
    
    cout << endl;
    cout << "---------------------------------------------------------------" << endl;
    
}

void searchLC(vector<string> &info,vector<string> &rooms,vector<string> cost ,vector<string> &status,string &key){
    cout << "---------------------------------------------------------------" << endl;
    unsigned int i = 0;
    unsigned int cosy = 0;
    unsigned int pass = 0;
    while(i < rooms.size()){
        if(status[i] == key && pass == 0) cout << "ห้องว่างที่สามารถเข้าพักได้ " << endl;
        cout << endl;
        if(stoi(cost[i]) == cosy){
            cout << "ห้องหมายเลข : " << rooms[i] << endl;
            cout << "ราคา : " << cost[i] << " บาท ต่อ คืน" << endl;
            cout << "รายละเอียด : " << info[i] << endl;
            cout << endl;
            pass++;
        }
        cosy += 100;
        i++;
    }
    if(i == rooms.size() && pass == 0) cout << "ไม่พบห้องพักที่สามารถเข้าพักได้" << endl;
    
    cout << endl;
    cout << "---------------------------------------------------------------" << endl;
    
}

void searchHC(vector &info,vector &rooms,vector cost ,vector &status,string &key){
    cout << "---------------------------------------------------------------" << endl;
    unsigned int i = 0;
    unsigned int cosy = 10000;
    unsigned int pass = 0;
    while(i < rooms.size()){
        if(status[i] == key && pass == 0) cout << "ห้องว่างที่สามารถเข้าพักได้ " << endl;
        cout << endl;
        if(stoi(cost[i]) == cosy){
            cout << "ห้องหมายเลข : " << rooms[i] << endl;
            cout << "ราคา : " << cost[i] << " บาท ต่อ คืน" << endl;
            cout << "รายละเอียด : " << info[i] << endl;
            cout << endl;
            pass++;
        }
        cosy -= 1000;
        i++;
    }
    if(i == rooms.size() && pass == 0) cout << "ไม่พบห้องพักที่สามารถเข้าพักได้" << endl;

    cout << endl;
    cout << "---------------------------------------------------------------" << endl;
}

int main(){
    string filename = "______"; //ชื่อไฟล์ข้อมูล***************************
    vector<string> info;
    vector<string> rooms;
    vector<string> cost;
    vector<string> status;
    importDataFromFile(filename, info, rooms, cost, status);
    
    do{
        string command, key;
        int rkey = 0;
        getCommand(command,key,rkey);
        key = toUpperStr(key);
        command = toUpperStr(command);
        if(command == "EXIT") break; // กด X เพื่อออกจากแถบค้นหา
        else if(command == "ROOMS") searchRooms(info, rooms, cost, status, rkey);
        else if(command == "STATUS") searchST(info, rooms,cost, status, key);
        else if(command == "LOWCOST") searchLC(info,rooms,cost,status,key);
        else if(command == "HIGHCOST") searchHC(info,rooms,cost,status,key);
    }while(true);
    
    return 0;
}
