### ISSUE TITLE
ระบบที่คิดไว้

### ISSUE THREAD

**Issue by Yay50210** [Yay50210/comPo#5]
คุยกันเรื่องระบบโดยรวมที่่จะมีในโปรแกรม การจัดการโรงแรม

**Comment by Yay50210** [comment]
![image](https://github.com/Yay50210/comPo/assets/141820412/455b3b54-fe74-403d-9aa7-62a95965656b)
![image](https://github.com/Yay50210/comPo/assets/141820412/4341e9b7-3041-4b4e-be3c-cc3adbf62c36)
![image](https://github.com/Yay50210/comPo/assets/141820412/de09dc88-f2b2-4d4d-b433-e8dbdb0f64b0)

ตัวอย่างเว็ปไซต์ https://www.rivertalesth.com/

**Comment by Buburry** [comment]
CppCMS c++ framework สำหรับ web

or Microsoft visual studio c++gui แล้วหาทางแปลงอีกที

**Comment by Buburry** [comment]
Qt
QtWebApp

**Comment by Buburry** [comment]
gmail vs code GHOGHO
