### ISSUE TITLE
การจองห้องพัก

### ISSUE THREAD

**Issue by Yay50210** [Yay50210/comPo#6]
ลูกค้า/เจ้าของ สามารถจองห้องพักได้ด้วยตนเอง

**Comment by Yay50210** [comment]
สร้างเครื่องหมายบอก การจอง ว่าจองแล้วหรือ ว่าง
![image](https://github.com/Yay50210/comPo/assets/141820412/e354698b-ceb5-4800-bbbc-9b6024281b48)

**Comment by Buburry** [comment]
Microsoft visual studio gui c++

**Comment by Teetat2146** [comment]
#ifndef DIALOG_H
#define DIALOG_H

#include <QDialog>

namespace Ui {
class Dialog;
}

class Dialog : public QDialog
{
    Q_OBJECT

public:
    explicit Dialog(QWidget *parent = nullptr);
    ~Dialog();

signals:
    void changetext();

private slots:
    void on_pushButton_clicked();

private:
    Ui::Dialog *ui;
};

#endif // DIALOG_H

**Comment by Teetat2146** [comment]
#include "dialog.h"
#include "ui_dialog.h"

Dialog::Dialog(QWidget *parent)
    : QDialog(parent)
    , ui(new Ui::Dialog)
{
    ui->setupUi(this);
}

Dialog::~Dialog()
{
    delete ui;
}


void Dialog::on_pushButton_clicked()
{
    emit changetext();
}

**Comment by Teetat2146** [comment]
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "dialog.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    void on_pushButton_clicked();
    void settext();


private:
    Ui::MainWindow *ui;
    Dialog *dialog;
};
#endif // MAINWINDOW_H

**Comment by Teetat2146** [comment]
#include "mainwindow.h"
#include "ui_mainwindow.h"

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow),
    dialog(nullptr)
{
    ui->setupUi(this);
    //connect(dialog, &Dialog::changetext, this, &MainWindow::settext);
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::on_pushButton_clicked()
{
    if (!dialog) {
        dialog = new Dialog(this);
        connect(dialog, &Dialog::changetext, this, &MainWindow::settext);
    }
    dialog->show();

}

void MainWindow::settext(){
    ui->label->setText("Success");

}
